; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Recoll"
#define MyAppVersion "1.43.13-20260223-qt_6_8_2-5979e72a"
#define MyAppPublisher "Recoll.org"
#define MyAppURL "http://www.recoll.org"
#define MyAppExeName "recoll.exe"
#define IdxAppName "Recollindex background indexer"
#define IdxAppExeName "recollindex.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E9BC39EC-0E3D-4DDA-8DA0-FDB8ED16DC8D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible
DefaultGroupName={#MyAppName}
OutputDir=C:\Temp
Compression=lzma
SolidCompression=yes
;; Use either prv=adm and defaultdir={pf} or prv=lowest and defaultdir=userpf
;PrivilegesRequired=lowest
;DefaultDirName={userpf}\{#MyAppName}
PrivilegesRequired=admin
DefaultDirName={commonpf}\{#MyAppName}
LicenseFile=D:\install\recoll\COPYING.txt
OutputBaseFilename=recoll-setup-{#MyAppVersion}
SetupIconFile=D:\install\recoll\Share\recoll.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; VC++ redistributable runtime. Extracted by VC2017RedistNeedsInstall(), if needed.
; Source: "D:\install\recoll\Share\dist\VC_redist.x64.exe"; DestDir: {tmp}; Flags: dontcopy

#ifndef StagingDir
#define StagingDir "..\..\staging"
#endif

; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "{#StagingDir}\bin\recoll.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#StagingDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{#IdxAppName}"; Filename: "{app}\{#IdxAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Parameters: "-m -w 0"; Flags: runminimized preventpinning
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[CustomMessages]
InstallingVCredist=Installing Microsoft VC++ redistributable

[Run]
Filename: "{tmp}\VC_redist.x64.exe"; \
  StatusMsg: "{cm:InstallingVCredist}"; \
  Parameters: "/quiet"; Check: VCRedistNeedsInstall; Flags: waituntilterminated
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function VCRedistNeedsInstall: Boolean;
var 
  Version: String;
begin
  if RegQueryStringValue(HKEY_LOCAL_MACHINE,
       'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64', 'Version',
       Version) then
  begin
    // Is the installed version at least ours ? 
    Log('VC Redist Version check : found ' + Version);
    Result := (CompareStr(Version, 'v14.42.34438.00')<0);
  end
  else 
  begin
    // Not even an old version installed
    Result := True;
  end;
  if (Result) then
  begin
    ExtractTemporaryFile('VC_redist.x64.exe');
  end;
end;
